/**********************************
 * @Author: Ronnie Zhang
 * @LastEditor: Ronnie Zhang
 * @LastEditTime: 2023/12/13 20:54:36
 * @Email: zclzone@outlook.com
 * Copyright © 2023 Ronnie Zhang(大脸怪) | https://isme.top
 **********************************/

export const defaultLayout = 'normal'

export const defaultPrimaryColor = '#316C72'

// 控制 LayoutSetting 组件是否可见
export const layoutSettingVisible = true

export const naiveThemeOverrides = {
  common: {
    primaryColor: '#316C72FF',
    primaryColorHover: '#316C72E3',
    primaryColorPressed: '#2B4C59FF',
    primaryColorSuppl: '#316C72E3',
  },
}

// const externalLinks = [
//   {
//     code: 'ExternalLink',
//     name: '外链(可内嵌打开)',
//     type: 'MENU',
//     icon: 'i-fe:external-link',
//     order: 98,
//     enable: true,
//     show: true,
//     children: [
//       {
//         code: 'ShowDocs',
//         name: '项目文档',
//         type: 'MENU',
//         path: 'https://isme.top',
//         icon: 'i-me:docs',
//         order: 1,
//         enable: true,
//         show: true,
//       },
//       {
//         code: 'ApiFoxDocs',
//         name: '接口文档',
//         type: 'MENU',
//         path: 'https://apifox.com/apidoc/shared-ff4a4d32-c0d1-4caf-b0ee-6abc130f734a',
//         icon: 'i-me:apifox',
//         order: 2,
//         enable: true,
//         show: true,
//       },
//       {
//         code: 'NaiveUI',
//         name: 'Naive UI',
//         type: 'MENU',
//         path: 'https://www.naiveui.com/zh-CN/os-theme',
//         icon: 'i-me:naiveui',
//         order: 3,
//         enable: true,
//         show: true,
//       },
//       {
//         code: 'MyBlog',
//         name: '博客-掘金',
//         type: 'MENU',
//         path: 'https://juejin.cn/user/1961184475483255/posts',
//         icon: 'i-simple-icons:juejin',
//         order: 4,
//         enable: true,
//         show: true,
//       },
//     ],
//   },
// ]

export const adminPermissions = [
  {
    // code: 'Dashboard',
    // name: '仪表盘',
    // type: 'MENU',
    // path: '/',
    // component: '/src/views/home/index.vue',
    // icon: 'i-carbon:home',
    // order: 0,
    // enable: true,
    // show: true,
    code: 'AdminDashboard',
    name: '数据大屏',
    type: 'MENU',
    path: '/',
    component: '/src/views/pms/dashboard/index.vue',
    icon: 'i-carbon:chart-line',
    order: 0,
    enable: true,
    show: true,
  },
  {
    code: 'Pms',
    name: '系统管理',
    type: 'MENU',
    icon: 'i-carbon:cloud-service-management',
    order: 1,
    enable: true,
    show: true,
    children: [
      {
        code: 'PmsUser',
        name: '用户管理',
        type: 'MENU',
        path: '/pms/user',
        component: '/src/views/pms/user/index.vue',
        icon: 'i-carbon:user-multiple',
        order: 1,
        enable: true,
        show: true,
      },
      {
        code: 'PmsRole',
        name: '角色管理',
        type: 'MENU',
        path: '/pms/role',
        component: '/src/views/pms/role/index.vue',
        icon: 'i-carbon:user-role',
        order: 2,
        enable: true,
        show: true,
      },
    ],
  },
  {
    code: 'CourseManagement',
    name: '课程管理',
    type: 'MENU',
    icon: 'i-carbon:education',
    order: 2,
    enable: true,
    show: true,
    children: [
      {
        code: 'PmsCourse',
        name: '课程管理',
        type: 'MENU',
        path: '/pms/course',
        component: '/src/views/pms/course/index.vue',
        icon: 'i-carbon:course',
        order: 1,
        enable: true,
        show: true,
      },
      {
        code: 'PmsChapter',
        name: '章节管理',
        type: 'MENU',
        path: '/pms/chapter',
        component: '/src/views/pms/chapter/index.vue',
        icon: 'i-carbon:book',
        order: 2,
        enable: true,
        show: true,
      },
      {
        code: 'PmsSection',
        name: '小节管理',
        type: 'MENU',
        path: '/pms/section',
        component: '/src/views/pms/section/index.vue',
        icon: 'i-carbon:document',
        order: 3,
        enable: true,
        show: true,
      },
      {
        code: 'PmsCourseSubject',
        name: '课程分类',
        type: 'MENU',
        path: '/pms/course-subject',
        component: '/src/views/pms/course-subject/index.vue',
        icon: 'i-carbon:category',
        order: 4,
        enable: true,
        show: true,
      },
      {
        code: 'PmsCourseComment',
        name: '课程评论',
        type: 'MENU',
        path: '/pms/course-comment',
        component: '/src/views/pms/course-comment/index.vue',
        icon: 'i-carbon:chat',
        order: 5,
        enable: true,
        show: true,
      },
      {
        code: 'PmsMyCourse',
        name: '我的课程',
        type: 'MENU',
        path: '/pms/my-course',
        component: '/src/views/pms/my-course/index.vue',
        icon: 'i-carbon:bookmark',
        order: 6,
        enable: true,
        show: true,
      },
    ],
  },
  {
    code: 'ContentManagement',
    name: '内容管理',
    type: 'MENU',
    icon: 'i-carbon:content-delivery-network',
    order: 3,
    enable: true,
    show: true,
    children: [
      {
        code: 'PmsAnnouncement',
        name: '公告管理',
        type: 'MENU',
        path: '/pms/announcement',
        component: '/src/views/pms/announcement/index.vue',
        icon: 'i-carbon:bullhorn',
        order: 1,
        enable: true,
        show: true,
      },
      {
        code: 'PmsAnnouncementCategory',
        name: '公告分类',
        type: 'MENU',
        path: '/pms/announcement-category',
        component: '/src/views/pms/announcement-category/index.vue',
        icon: 'i-carbon:category-new',
        order: 2,
        enable: true,
        show: true,
      },
      {
        code: 'PmsCarousel',
        name: '轮播图管理',
        type: 'MENU',
        path: '/pms/carousel',
        component: '/src/views/pms/carousel/index.vue',
        icon: 'i-carbon:image-search',
        order: 3,
        enable: true,
        show: true,
      },
    ],
  },
  {
    code: 'HomeworkManagement',
    name: '作业管理',
    type: 'MENU',
    icon: 'i-carbon:task',
    order: 4,
    enable: true,
    show: true,
    children: [
      {
        code: 'PmsHomework',
        name: '作业列表',
        type: 'MENU',
        path: '/pms/homework',
        component: '/src/views/pms/homework/index.vue',
        icon: 'i-carbon:task-view',
        order: 1,
        enable: true,
        show: true,
      },
      {
        code: 'PmsHomeworkSubmission',
        name: '作业提交',
        type: 'MENU',
        path: '/pms/homework-submission',
        component: '/src/views/pms/homework-submission/index.vue',
        icon: 'i-carbon:task-complete',
        order: 2,
        enable: true,
        show: true,
      },
    ],
  },
  {
    code: 'DataAnalysis',
    name: '数据分析',
    type: 'MENU',
    icon: 'i-carbon:analytics',
    order: 5,
    enable: true,
    show: true,
    children: [
      {
        code: 'PmsStatistics',
        name: '统计仪表板',
        type: 'MENU',
        path: '/pms/statistics',
        component: '/src/views/pms/statistics/index.vue',
        icon: 'i-carbon:dashboard',
        order: 1,
        enable: true,
        show: true,
      },
      {
        code: 'PmsCourseBrowse',
        name: '课程浏览',
        type: 'MENU',
        path: '/pms/course-browse',
        component: '/src/views/pms/course-browse/index.vue',
        icon: 'i-carbon:view',
        order: 2,
        enable: true,
        show: true,
      },
      {
        code: 'PmsOrderManagement',
        name: '订单管理',
        type: 'MENU',
        path: '/pms/order-management',
        component: '/src/views/pms/order-management/index.vue',
        icon: 'i-carbon:shopping-cart',
        order: 3,
        enable: true,
        show: true,
      },
    ],
  },
  // ...externalLinks,
]

export const teacherPermissions = [
  {
    // code: 'Dashboard',
    // name: '仪表盘',
    // type: 'MENU',
    // path: '/',
    // component: '/src/views/teacherhome/index.vue',
    // // component: '/src/views/teacherhome/dashboard.vue',
    // icon: 'i-carbon:home',
    // order: 0,
    // enable: true,
    // show: true,
    code: 'TeacherDashboard',
    name: '数据大屏',
    type: 'MENU',
    path: '/',
    component: '/src/views/teacherhome/dashboard/index.vue',
    icon: 'i-carbon:chart-line',
    order: 0,
    enable: true,
    show: true,
  },
  {
    code: 'CourseTeaching',
    name: '课程教学',
    type: 'MENU',
    icon: 'i-carbon:education',
    order: 1,
    enable: true,
    show: true,
    children: [
      {
        code: 'TeacherMyCourse',
        name: '我的课程',
        type: 'MENU',
        path: '/teacherhome/course',
        component: '/src/views/teacherhome/course/index.vue',
        icon: 'i-carbon:course',
        order: 1,
        enable: true,
        show: true,
      },
      {
        code: 'TeacherChapter',
        name: '章节管理',
        type: 'MENU',
        path: '/teacherhome/chapter',
        component: '/src/views/teacherhome/chapter/index.vue',
        icon: 'i-carbon:book',
        order: 2,
        enable: true,
        show: true,
      },
      {
        code: 'TeacherSection',
        name: '小节管理',
        type: 'MENU',
        path: '/teacherhome/section',
        component: '/src/views/teacherhome/section/index.vue',
        icon: 'i-carbon:document',
        order: 3,
        enable: true,
        show: true,
      },
    ],
  },
  {
    code: 'HomeworkTeaching',
    name: '作业管理',
    type: 'MENU',
    icon: 'i-carbon:task',
    order: 2,
    enable: true,
    show: true,
    children: [
      {
        code: 'TeacherHomework',
        name: '作业发布',
        type: 'MENU',
        path: '/teacherhome/homework',
        component: '/src/views/teacherhome/homework/index.vue',
        icon: 'i-carbon:task-add',
        order: 1,
        enable: true,
        show: true,
      },
      {
        code: 'TeacherGrade',
        name: '作业批改',
        type: 'MENU',
        path: '/teacherhome/grade',
        component: '/src/views/teacherhome/grade/index.vue',
        icon: 'i-carbon:task-complete',
        order: 2,
        enable: true,
        show: true,
      },
      {
        code: 'TeacherSubmissionManage',
        name: '作业提交管理',
        type: 'MENU',
        path: '/teacherhome/submission-manage',
        component: '/src/views/teacherhome/submission-manage/index.vue',
        icon: 'i-carbon:task-view',
        order: 3,
        enable: true,
        show: true,
      },
    ],
  },
  {
    code: 'StudentManagement',
    name: '学员管理',
    type: 'MENU',
    icon: 'i-carbon:user-study',
    order: 3,
    enable: true,
    show: true,
    children: [
      {
        code: 'TeacherMyCourseStudents',
        name: '我的学员',
        type: 'MENU',
        path: '/teacherhome/my-course-students',
        component: '/src/views/teacherhome/my-course-students/index.vue',
        icon: 'i-carbon:user-multiple',
        order: 1,
        enable: true,
        show: true,
      },
      {
        code: 'TeacherCourseComment',
        name: '课程评论',
        type: 'MENU',
        path: '/teacherhome/course-comment',
        component: '/src/views/teacherhome/course-comment/index.vue',
        icon: 'i-carbon:chat',
        order: 2,
        enable: true,
        show: true,
      },
    ],
  },
  {
    code: 'TeachingAnalysis',
    name: '教学分析',
    type: 'MENU',
    icon: 'i-carbon:analytics',
    order: 4,
    enable: true,
    show: true,
    children: [
      {
        code: 'TeacherStatistics',
        name: '数据统计',
        type: 'MENU',
        path: '/teacherhome/statistics',
        component: '/src/views/teacherhome/statistics/index.vue',
        icon: 'i-carbon:chart-line',
        order: 1,
        enable: true,
        show: true,
      },
      {
        code: 'TeacherCourseView',
        name: '课程浏览',
        type: 'MENU',
        path: '/teacherhome/course-view',
        component: '/src/views/teacherhome/course-view/index.vue',
        icon: 'i-carbon:view',
        order: 2,
        enable: true,
        show: true,
      },
      {
        code: 'TeacherRevenue',
        name: '收入管理',
        type: 'MENU',
        path: '/teacherhome/revenue',
        component: '/src/views/teacherhome/revenue/index.vue',
        icon: 'i-carbon:currency-dollar',
        order: 3,
        enable: true,
        show: true,
      },
    ],
  },
  {
    code: 'AIAssistant',
    name: 'AI助手',
    type: 'MENU',
    icon: 'i-carbon:education',
    order: 5,
    enable: true,
    show: true,
    children: [
      {
        code: 'CoursewareAssistant',
        name: 'AI 课件助手',
        type: 'MENU',
        path: '/teacherhome/manus-chat',
        component: '/src/views/teacherhome/manus-chat/index.vue',
        icon: 'i-carbon:education',
        order: 1,
        enable: true,
        show: true,
      },
    ],
  },

  // ...externalLinks,
]
